### PR TITLE
feat: UserFormatContext

### PR DESCRIPTION
**Pull request by giautm**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

Close: https://github.com/GetStream/stream-chat-react-native/issues/794

To enable custom format, in the App component provide `FormatProvider` with custom functions:
```tsx
import { UserFormatProvider } from 'stream-chat-react-native'

const anonymousFormat = {
  formatImage: () => undefined,
  formatName: () => 'Anonymous',
};

function App(props: any) {
  <UserFormatProvider value={anonymousFormat}>
    {props.children}
  </UserFormatProvider>;
}
```

### CODE REVIEW

**Comment by giautm** [comment]
Hi @vishalnarkhede, do you review it yet?

**Comment by vishalnarkhede** [comment]
@giautm what kind of formatting are you looking for around name and image?

**Comment by giautm** [comment]
> @giautm what kind of formatting are you looking for around name and image?

As I said in the issue #794,

> I have a group chat with employers from companies, they chat as their company. So, I have to show Company Logo and Company Name instead of their name. All information ready attached to User profile. But I can't custom it for now.

The current implement in our apps:
```tsx
function useActorFormat<
  Us extends DefaultUserType = LocalUserType
>(): CustomFormats<Us> {
  const actor = useContext(ActorContext)

  const formatAvatar = useCallback(
    (user?: UserResponse<Us> | null): string | undefined => {
      // @ts-ignore we should put actor on user type to avoid this
      const companyImage = user?.company?.image ?? ''
      if (actor === 'worker') {
        return companyImage
      }

      return user?.image
    },
    [actor],
  )

  const formatName = useCallback(
    (user?: UserResponse<Us> | null): string => {
      // @ts-ignore we should put actor on user type to avoid this
      const companyName = user?.company?.name ?? ''
      if (actor === 'worker') {
        return companyName
      }

      if (companyName) {
        return `${companyName} - ${user?.name}`
      }

      return user?.name ?? user?.username ?? user?.id ?? ''
    },
    [actor],
  )

  return { formatAvatar, formatName }
}
```

**Comment by giautm** [comment]
Hi @vishalnarkhede, any blocking on this?

**Comment by giautm** [comment]
Hi @vishalnarkhede, please give any feedback about this PR.

**Comment by vishalnarkhede** [comment]
Hey @giautm we have added this task in our backlog. I think few simple props should do the trick instead of introducing another context, which users of this library need to provide. We will pick it up soon and get it published.

Thanks for the effort here.

**Comment by giautm** [comment]
No, User don't need to provider any new Provider if they don't use this feature. Because, in the default context value is implement the default logic as previewly.

**Pull request closed without merging**
