### PR TITLE
chore: rename master to main

### PR DESCRIPTION
**Pull request by madsroskar**
## 🎯 Goal

There's no reason for us to keep our main branch's outdated `master` naming. This PR aims to update all references to the branch to be `main` so we can safely rename it. 

## 🛠 Implementation details

`git grep -lz 'master' | xargs -0 perl -i'' -pE "s/master/main/g"`

## 🧪 Testing

N/A

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec
- [ ] New code is covered by tests
- [ ] Screenshots added for visual changes
- [x] Documentation is updated

### CODE REVIEW

**Review by vishalnarkhede — APPROVED** [review]
looks good otherwise

**Comment by madsroskar** [comment]
> Why did the translation files change?

It looks like it's the prettier config that's sorting them alphabetically - I had to run the `lint-fix` command. Not sure why this hasn't happened in other PRs tbh 🤔

**Review by santhoshvai — APPROVED** [review]
LGTM

**Review by vanGalilea — APPROVED** [review]

**Pull request merged**
