### PR TITLE
Refactor: design fixes in pinned message feature

### PR DESCRIPTION
**Pull request by khushal87**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request
This PR introduces design fixes in the pinned message functionality.
The following are the fixes:
- Color inconsistencies in dark and light mode.
- Change of Icon of Pinned Message Label
- Improve theme colors for highlighted text and reaction bubble.

### CODE REVIEW

**Review by vishalnarkhede — APPROVED** [review]

**Comment by vishalnarkhede** [comment]
I think this should go as `refactor: ...`.

**Comment by vishalnarkhede** [comment]
But no worries, I will adjust it within merge commit...just a notice for future

**Comment by tsirlucas** [comment]
if you change the pr title it should work as well

**Comment by khushal87** [comment]
Done @vishalnarkhede @tsirlucas

**Pull request merged**
