### PR TITLE
feat: improve performance in message-list by reducing api calls using the improved 2-way pagination api [CRNS-462]

### PR DESCRIPTION
**Pull request by santhoshvai**
## 🎯 Goal

The backend has recently introduced support for querying messages around a certain message-id or certain date. The JS SDK has added support for it and we want to use this API for our pagination. Additionally, the JS SDK has support for disjoint message sets. Using these sets we can avoid clearing the messages in the channel and reduce our API calls.

## 🛠 Implementation details

- Use the `loadMessageIntoState` method in the channel state to jump to a particular message.
- Avoid clearing the messages of a channel while making queries.
- Do not set `isUpToDate` field to false anymore when making queries around a message. This is because we still want to watch for new messages while a jump has happened and add them to the message set in the JS SDK.

## 🎨 UI Changes

NA

## 🧪 Testing

Would be nice to have detox tests around jumping a message. But detox support with FlatList has been historically flaky and we have to look into this separately in my view.

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec
- [ ] New code is covered by tests
- [ ] Screenshots added for visual changes
- [x] Documentation is updated

### CODE REVIEW

**Comment by vishalnarkhede** [comment]
@santhoshvai did some testing. I am sharing the loom recording since its easier to demonstrate the issues.

https://www.loom.com/share/604fcbc409de4e7da83c20650b720a15

But great job with this stuff, its quite a complex one!! 🎉

**Comment by vanGalilea** [comment]
Good work @santhoshvai. Let's fix the regression, I'm curious to know what is causing the issues around the scroll to bottom button and unread messages state not being reset.

**Comment by santhoshvai** [comment]
@vanGalilea The issues in the shared loom video have been fixed. There is one more edge case that is caused by the limitations of the flat-list.  It is the slowness of moving to a message when the message is far out, say more than 200 indexes away and if all the messages have been loaded but messages are not rendered. This happens due to the lazy rendering of flatlist. I have increased the `maxToRenderPerBatch` to make it a little bit better ([commit - 1b81f49](https://github.com/GetStream/stream-chat-react-native/pull/1239/commits/1b81f49096ea8d5eff4ffb5347c938fe717aaa77)). But @vishalnarkhede is going to check if this is enough or not needed or if we have to take the time to find a better solution.

**Comment by vanGalilea** [comment]
> Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=GetStream_stream-chat-react-native&pullRequest=1239)
> 
> [Bug](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=CODE_SMELL) [6 Code Smells](https://sonarcloud.io/project/issues?id=GetStream_stream-chat-react-native&pullRequest=1239&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1239) No Coverage information [](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1239&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=GetStream_stream-chat-react-native&pullRequest=1239&metric=new_duplicated_lines_density&view=list)

@santhoshvai can you please handle the code smells?

**Review by vishalnarkhede — APPROVED** [review]

**Pull request merged**
