### PR TITLE
fix: update refreshList reference

### PR DESCRIPTION
**Pull request by giautm**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

Close https://github.com/GetStream/stream-chat-react-native/issues/832

### CODE REVIEW

**Comment by vishalnarkhede** [comment]
@giautm thanks for the PR. But shouldn't it be resolved by simply putting `refreshList` as part of useEffect dependency?

**Comment by giautm** [comment]
> @giautm thanks for the PR. But shouldn't it be resolved by simply putting `refreshList` as part of useEffect dependency?

No, because refreshList didnot wrap by useCallback yet

**Comment by vishalnarkhede** [comment]
@giautm can you fix the linter issue?

**Comment by giautm** [comment]
> @giautm can you fix the linter issue?

@vishalnarkhede : I'm done.

**Comment by giautm** [comment]
Hey @vishalnarkhede, I don't know why the CI failed.

**Comment by vishalnarkhede** [comment]
@giautm yeah I am checking the PR right now. I will take over from here:)

**Pull request merged**
