### PR TITLE
fix for #78

### PR DESCRIPTION
**Pull request by capacitivellc**
# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [X] Code changes are tested (add some information if not applicable)

### CODE REVIEW

**Comment by capacitivellc** [comment]
@tbarbugli Hi. I reverted the package.json changes. As for the bug, yes it is very easy to recreate. in fact it happens on any fresh install of package into a new RN project. The library 'react-native-image-picker' actually expects an options object. i.e. ```const options = {
  title: 'Select Avatar',
  customButtons: [{ name: 'fb', title: 'Choose Photo from Facebook' }],
  storageOptions: {
    skipBackup: true,
    path: 'images',
  },
};
```, but it accepts an empty object, not `null`.

**Comment by tbarbugli** [comment]
@vishalnarkhede this LGTM can you check and if OK merge and release?

**Comment by vishalnarkhede** [comment]
Checking ... !!

**Comment by vishalnarkhede** [comment]
@capacitivellc looks good and thanks for this. Seems like they changed it recently, their documentation still says that `null` is acceptable.

Screen Shot 2019-12-03 at 2 04 15 PM


Merging it !!

**Pull request merged**
