### PR TITLE
refactor: drop offline cachine layer

### PR DESCRIPTION
**Pull request by vishalnarkhede**
## 🎯 Goal

Revert the offline cachine

### CODE REVIEW

**Review by madsroskar — APPROVED** [review]
LGTM

**Comment by vishalnarkhede** [comment]
I have created a tag from v4 branch - [offline-caching](https://github.com/GetStream/stream-chat-react-native/releases/tag/offline-caching-layer)

**Review by khushal87 — COMMENTED** [review]
LGTM 🚀

**Comment by madsroskar** [comment]
@vishalnarkhede How did you go about doing this? It seems to me like there still are things on v4.0.0 from offline support commits, which can make sense if it was done manually but a little more tricky if you made the changes manually

**Comment by mfbx9da4** [comment]
@vishalnarkhede Why was offline caching removed? Is it being superseded? What is the current guidance for adding local caching? I've added this issue to the core repo https://github.com/GetStream/stream-chat-js/issues/891

**Pull request merged**
