### PR TITLE
feat: add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by arthurgeron**
## 🎯 Goal
- Add Brazilian Portuguese translation

## 🛠 Implementation details
- Added relevant info to translations doc

## 🎨 UI Changes

N/A

## 🧪 Testing

Use `Streami18n` and set language to `pt-BR`

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Documentation is updated
- [x] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

**Review by carolinaknoll — APPROVED** [review]
Awesome work! Thanks for adding the Portuguese translation, I'm sure it will benefit people who need it in the future 🚀

**Review by gc0rtes — COMMENTED** [review]
Hi guys,  I’ve some suggestions. Instead of the “first” sentence I suggest changing it to the “second” sentence, as follow:
“Cannot Flag Message”: “Não é possível sinalizar a mensagem” to “Não é possível reportar a mensagem”
“Flag”: “Sinalizar” to “Reportar”
“Flag Message” : “Sinalizar Mensagem” to “Reportar Mensagem”
“Flag action failed either due to a network issue or the message is already flagged” : “A ação de sinalização falhou devido a um problema de rede ou a mensagem já está sinalizada.”  to “A ação para reportar a mensagem falhou devido a um problema de rede ou a mensagem já foi reportada.”
“Sending links is not allowed in this conversation” : “Enviar links não é permitido nesta conversa” to “Não é permitido enviar links nesta conversa”
“Unmute User” : “Ativar Som do Usuário” to “Remover usuário do modo silencioso”
“Unpin from Conversation” : “Desfixar da Conversa” to “Desmarcar como fixado na conversa”
“Thread Reply” : “Respostas de Thread” to “Respostas de Tópico”

**Comment by carolinaknoll** [comment]
@gc0rtes I really like your suggestions! In fact as I was reading the commit changes the first time I spent some time thinking how to make the "Unmute User" message better but couldn't come up with anything better. I'm glad you could! 😄

**Comment by arthurgeron-work** [comment]
Applied suggestions made by @gc0rtes

**Comment by arthurgeron** [comment]
Git auto-closed this when I updated my fork's develop branch, re-opened it over [here](https://github.com/GetStream/stream-chat-react-native/pull/2224).

**Pull request closed without merging**
