### PR TITLE
Typescript Setup

### PR DESCRIPTION
**Pull request by DanC5**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request

TS config setup

### CODE REVIEW

**Comment by virdesai** [comment]
also a merge conflict

**Comment by vishalnarkhede** [comment]
Should we hold this one until we are actually ready to start typescripting components?

**Comment by virdesai** [comment]
> Should we hold this one until we are actually ready to start typescripting components?

🤷 up to you. it's just the base setup really

**Comment by DanC5** [comment]
> Should we hold this one until we are actually ready to start typescripting components?

Shouldn't matter too much since like Vir said it's just config files. Might be nice to merge it in so we don't have to keep updating this branch with 2.0, but also as soon as we get the TS setup in we'll have to start committing with no verify until we can fix all the warnings/errors found on the TS compile.

**Comment by virdesai** [comment]
> > Should we hold this one until we are actually ready to start typescripting components?
> 
> Shouldn't matter too much since like Vir said it's just config files. Might be nice to merge it in so we don't have to keep updating this branch with 2.0, but also as soon as we get the TS setup in we'll have to start committing with no verify until we can fix all the warnings/errors found on the TS compile.

could just disable tsc until we get to that point

**Comment by giautm** [comment]
I recommend to use https://github.com/react-native-community/bob to setup Typescript for the project. We also can use mono repos with yarn and lerna to easy testing package with example apps.

**Pull request merged**
