### PR TITLE
CRNS-58, 59: Adding support for custom message length in Channel preview

### PR DESCRIPTION
**Pull request by vishalnarkhede**
Fixes https://github.com/GetStream/stream-chat-react-native/issues/122 and https://github.com/GetStream/stream-chat-react-native/issues/121

# Submit a pull request

## CLA

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

### CODE REVIEW

**Comment by jaapbakker88** [comment]
@vishalnarkhede do we allow people to change the date on normal messages as well?

**Comment by vishalnarkhede** [comment]
> @vishalnarkhede do we allow people to change the date on normal messages as well?

Not yet!! Should we add it?

**Comment by vishalnarkhede** [comment]
@jaapbakker88 done!!

**Comment by jaapbakker88** [comment]
This looks great, remind me to add this to stream-chat-react as well.

**Pull request merged**
