### PR TITLE
feat: add portuguese translation

### PR DESCRIPTION
**Pull request by arthurgeron**
## 🎯 Goal
- Add Brazilian Portuguese translation

## 🛠 Implementation details
- Added relevant info to translations doc

Continuation of PR #2120 

## 🎨 UI Changes

N/A

## 🧪 Testing

Use `Streami18n` and set language to `pt-BR`

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Documentation is updated
- [x] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

**Comment by khushal87** [comment]
Hey @arthurgeron, sorry for a delayed response on the PR. Can you please resolve the conflicts and make sure all the new keys are added to your PR as per https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/i18n/en.json. Thanks 😄

**Comment by khushal87** [comment]
Hey, @arthurgeron, the PR is getting stale. Can you look into the comment above and update the translations accordingly. Thanks 😄

**Comment by arthurgeron** [comment]
> Hey, @arthurgeron, the PR is getting stale. Can you look into the comment above and update the translations accordingly. Thanks 😄

@khushal87  Thanks for the nudge! Noted that the PR had been pending for quite a while. Currently swamped, but I'll circle back to it when possible. Meanwhile, feel free to jump in and update the translations if you have the bandwidth.

**Comment by khushal87** [comment]
Hey @arthurgeron, since this PR is on your fork, I am not sure if I have the right to push. 😄

**Comment by khushal87** [comment]
Hey @arthurgeron, I have pushed the changes to your PR and is now merging it. Thanks 😄

**Pull request merged**
