### PR TITLE
feat: add prop for helping multiple channel list implementation

### LINKED ISSUE #1945: Multiple channel lists in RN - what's the best approach to handle it?
What's the correct way to have multiple channel lists in the React-Native app?

It seems that there is documentation about default behavior (that I also noticed in the RN), but for React there is support to handle that https://getstream.io/chat/docs/sdk/react/guides/multiple_channel_lists/#channelrenderfilterfn-prop

Is there a similar approach for RN? Some functions like `channelRenderFilterFn `?

My question for this is because it seems that when there are multiple channel lists i.e. A and B, and when the user sends the message from the channel (list A) then the channel also appears in channel list B, and none of the events handles gets called but the channel just gets added.

### PR DESCRIPTION
**Pull request by santhoshvai**
## 🎯 Goal

* fixes #1945 
* Also wanted by Feeld

## 🛠 Implementation details

did the exact same thing as done in react SDK. https://getstream.io/chat/docs/sdk/react/guides/multiple_channel_lists/#channelrenderfilterfn-prop

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [x] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

**Review by vanGalilea — APPROVED** [review]
All tested 👍🏻 LGTM

**Comment by mishkeTz** [comment]
Thank you!

**Comment by santhoshvai** [comment]
@mishkeTz thank you for filing the issue as well

**Pull request merged**
