### PR TITLE
Add support for Custom Icons in SendButton

### PR DESCRIPTION
**Pull request by Pranav-Dakshina**
# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ ] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Description of the pull request
- This PR adds functionality to support custom icons in SendButton both for editing Icon and new message Icon.

### CODE REVIEW

**Comment by vishalnarkhede** [comment]
Hey @Pranav-Dakshina , thanks for the PR. But we already have option to add provide `SendButton` component to MessageInput. On top of that, I am not sure if its really necessary to add icon customizability as well.

**Comment by familywiser1** [comment]
@vishalnarkhede - We also like to change the icon since our primary theme is green whereas the send icon is blue. 

I know we can pass the "SendButton" to MessageInput. However, I am not sure how to do that without having to override other props of SendButton. I will appreciate if you can provide a code sample. thanks

**Comment by vishalnarkhede** [comment]
@familywiser1 You just need to add custom component as SendButton, like following!
```
<MessageInput
    SendButton={(props) => {
        <TouchableOpacity onPress={props.sendMessage}>
            <Image source={custom_icon} />
        </TouchableOpacity>
    }}
```

**Comment by vishalnarkhede** [comment]
Closing this for now. @Pranav-Dakshina let me know if you have more questions :) 

Thanks anyways for PR though!

**Pull request closed without merging**
