### PR TITLE
feat: add theming support for the chevron icon in scroll to bottom button

### LINKED ISSUE #1310: Support theming of chevron icon color in scroll to bottom button
**Describe what you would like to achieve**
Changing the chevron icon in the scroll to bottom button

**Expected behavior**
Chevron will change color, after specifying it in the theme object

**Additional context**
Only options at the moment are 

```
scrollToBottomButton: {
            container: ViewStyle;
            touchable: ViewStyle;
            unreadCountNotificationContainer: ViewStyle;
            unreadCountNotificationText: TextStyle;
            wrapper: ViewStyle;
};
```

**Screenshots**

<br/>

gz#22583

### PR DESCRIPTION
**Pull request by khushal87**
## 🎯 Goal

Fixes #1310 

## 🛠 Implementation details

Added the theme property `chevronColor` to the component using our global theme.

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec
- [ ] New code is covered by tests
- [x] Screenshots added for visual changes
- [ ] Documentation is updated

### CODE REVIEW

**Review by vanGalilea — COMMENTED** [review]
@khushal87 Is this sufficiently documented? (TS only)

**Review by vanGalilea — COMMENTED** [review]
@khushal87 Is this sufficiently documented? (TS only)

**Review by vanGalilea — APPROVED** [review]

**Comment by khushal87** [comment]
@vanGalilea We should deal with the theme documentation separately as we don't do it for any of the keys currently in our components. We should pick this up as a task to improve our documentation around theming 😄

**Pull request merged**
