### PR TITLE
fix: Add the correct styling for CooldownTimer

### PR DESCRIPTION
**Pull request by madsroskar**
## 🎯 Goal

Changing the styling of the CooldownTimer to match the [figma designs](https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Design-Kit---Current-version?node-id=12254%3A953)

## 🛠 Implementation details

One quirk I'm doing is to check for the amount of characters are displayed as the remaining seconds, as without it, going through 13, 12, 11, 10 the countdown jumped in width from character to character. As seen in the supplied video, this works around that.

I don't think this makes a difference of significance/that can be noticed since the component rerenders every second anyways, and it's a cheap calculation to make, so I haven't optimized it at all. If anybody thinks we should, I'm all ears.

## 🎨 UI Changes

https://user-images.githubusercontent.com/1548276/143273889-c7e3e290-33eb-4bd1-98f6-cfa0e7d3556e.mp4

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [x] Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec
- [ ] New code is covered by tests
- [x] Screenshots added for visual changes
- [ ] Documentation is updated

### CODE REVIEW

**Comment by vishalnarkhede** [comment]
Designs also show placeholder on inputbox

**Comment by madsroskar** [comment]
> Designs also show placeholder on inputbox

Ah, didn't notice heh. 2 min, updating

**Review by vishalnarkhede — APPROVED** [review]

**Comment by vishalnarkhede** [comment]
Merging this, but add the `cooldownActive` prop to component docs as well

**Comment by madsroskar** [comment]
> Merging this, but add the `cooldownActive` prop to component docs as well

#1019 addresses this now, thanks for pointing it out

**Pull request merged**
