### PR TITLE
fix: Stream chat fix http no such file

### PR DESCRIPTION
**Pull request by netoya**
## 🎯 Goal

Fix issue when upload audio in android.
IOS ??

## 🛠 Implementation details

Replace : and . in sample name audio record

### Replicate error
Create a new React Native project
Follow steps in getStream page for RN
Add .aac and mime audio/aac en Overview Panel
Enable audioRecording in the chat
Try to send audio
Audio upload file
See logs in GetStream Board: http: no such file. status 400

### CODE REVIEW

**Comment by netoya** [comment]
@khushal87. 
## Inside the component
When you want upload a audio record using default MessageInput component. 
The MessageInput use UploadVoiceRecording. 
Inside that, the default name is
```
name: `audio_recording_${new Date().toISOString()}.aac`,
```
For example:
audio_recording_2024-05-14T23:58:56.007Z.aac

## Inside the Stream's dashboard:
You can configure the extension and MIME type allowed for the upload.
extension: .aac
MIME type: audio/aac

## What's happen?
I try upload:
Using "audio_recording.aac". Upload work ✅
Using "audio_recording_2024-05-14T23:58:56.007Z.aac". Upload fail ❌

## How I fixed that
Change audio default name. 
Remplace unsupport chars in file name.
Trying. They are colon and dot

**Comment by khushal87** [comment]
Hey @netoya, can you run `yarn lint-fix` on the root of the project and push with fixed lint issues? Currently, the CI fails.

**Comment by netoya** [comment]
ready

**Comment by khushal87** [comment]
Thanks for the contribution. @netoya 🚀

**Pull request merged**
