### PR TITLE
Update to  expo sdk-34: permissions, document-picker and image-picker  as separate packages

### PR DESCRIPTION
**Pull request by agustif**
# Submit a pull request

## CLA
Official commennts on expo blog: https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319

`Required modular imports
In SDK 33, we deprecated imports from the monolith expo package in favor of installing and importing from individual module packages like expo-file-system. With SDK 34, we’ve fully removed the ability to import most modules from the expo package. This means that if you try to import { FileSystem } from 'expo';, you’ll now see an error instead of a warning.
In SDK 34, you will need to use the expo install command to install modules; this command is a wrapper around npm install/yarn add that automatically installs a module version compatible with your SDK version. For example, for the FileSystem module, you should run expo install expo-file-system and use import * as FileSystem from 'expo-file-system';.
This change paves the way for tree-shaking and smaller JavaScript bundles. It also makes moving between Expo’s managed and bare workflows simpler. To make the transition smoother, we’re providing expo-codemod, a command line utility that will parse your JS and automatically update any affected imports. Instructions are on the linked README page.`

We can use expo-codemod instead maybe
I think expo has recently spun off Permissions to a separate package on it's monorepo

https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/permissions.md
https://www.npmjs.com/package/expo-permissions
https://github.com/expo/expo/tree/master/packages/expo-permissions
https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/permissions.md

Just expo install expo-permissions and changing up the import in the index.js
maybe it should be import * as Permissions instead of 

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [X] Code changes are tested (add some information if not applicable)
No tests but it builds and passes prettier/linting.
## Description of the pull request

After trying the tutorial I got a warning about using expo-permissions, this should fix it

### CODE REVIEW

**Comment by agustif** [comment]
Not sure but maybe we can drop expo altogether now that the three used components are imported as separate packages instead?

**Comment by vishalnarkhede** [comment]
@agustif thank you for this pull request. Is it backward compatible? I mean will it work on apps which use Expo 33 or 32?

**Comment by agustif** [comment]
> @agustif thank you for this pull request.

Hi @vishalnarkhede, no problem, trying to solve my own issue here as I was already using expo v34 (latest) when tried to add stream-chat to my app!

> Is it backward compatible? I mean will it work on apps which use Expo 33 or 32?
I'm not sure but I don't see why not? It seems all code remains the same, and only imports and dependencies are managed as separated packages in order to improve code splitting/tree shaking in the future, by only requiring the add-ons one needs, and not having a fat expo-core.

At least that is what I read into the changelog update linked, do give it a look, maybe just try the code and see if it breaks!

On a final note,
I have tried to use my local version, but as you guys have two packages on one repo, I can't just really swap it for my github repo and try, and would have to publish to npm or know how to test it?

Can you give me any hints?

I also tried having the folder in my /Code and linking like ../stream-chat-react-/expo-package

**Comment by vishalnarkhede** [comment]
Hey @agustif , I did some testing on sample app with expo 32. But this thing fails because in expo 32, these standalone packages run into linking issues. 

On somewhat similar lines, I had to add some extra steps to keep it compatible with expo 32. Here is the pull request for it. Its not yet merged (am waiting for team's review), but you can take a look at it as well and let me know your opinion - https://github.com/GetStream/stream-chat-react-native/pull/58

**Comment by agustif** [comment]
> Hey @agustif , I did some testing on sample app with expo 32. But this thing fails because in expo 32, these standalone packages run into linking issues.
> 
@vishalnarkhede That's great news! I'm glad you could figure it out!
> On somewhat similar lines, I had to add some extra steps to keep it compatible with expo 32. Here is the pull request for it. Its not yet merged (am waiting for team's review), but you can take a look at it as well and let me know your opinion - #58
 I didn't knew you could do else on import statements!
Hope the team gives the green light to it, can't wait to keep integrating your products and services with my react website and expo-rn app.

Thanks for all the support, would be awesome if I could help out more on the project!

one last question, is there any roadmap for the rn implementation? do you have any community/slack for the stream open source projects?

**Comment by vishalnarkhede** [comment]
Hey @agustif ,

>  is there any roadmap for the rn implementation?

We already have react-native sdk

 **Usage** -  https://github.com/GetStream/stream-chat-react-native#native-package
 **Source Code** - https://github.com/GetStream/stream-chat-react-native/tree/master/native-package

> do you have any community/slack for the stream open source projects?

We do have slack for public discussions. If you give me your email address, I can add you there. 

**P.S.** You can close this pull request now that v0.2.1 has support for expo 34 and 33. I have merged the PR. Thanks alot for help and feedbacks :)

**Comment by agustif** [comment]
Thank you for such fast resolution, already working on my project with expo v34!!

**Comment by agustif** [comment]
> We do have slack for public discussions. If you give me your email address, I can add you there.

me@agusti.me

Thanks for the v0.2.1 upgrade!

**Pull request closed without merging**
